#!/bin/bash 

rm a.out *.bc *.ll

/opt/llvm-svn/bin/clang -emit-llvm -S test-are.c -o test-are.ll
/opt/llvm-svn/bin/llc test-are.ll -o test-are.s

/opt/llvm-svn/bin/clang -emit-llvm test-are.c -c -o test-are.bc
/opt/llvm-svn/bin/lli test-are.bc

/opt/llvm-svn/bin/opt -load /opt/llvm-svn/lib64/DragonBallARE.so -dragonball-are-func < test-are.bc > test-are-func.bc
/opt/llvm-svn/bin/lli test-are-func.bc
/opt/llvm-svn/bin/llvm-dis test-are-func.bc -o test-are-func.ll
/opt/llvm-svn/bin/llc test-are-func.ll -o test-are-func.s

/opt/llvm-svn/bin/opt -load /opt/llvm-svn/lib64/DragonBallARE.so -dragonball-are-cfg < test-are.bc > test-are-cfg.bc
/opt/llvm-svn/bin/lli test-are-cfg.bc
/opt/llvm-svn/bin/llvm-dis test-are-cfg.bc -o test-are-cfg.ll
/opt/llvm-svn/bin/llc test-are-cfg.ll -o test-are-cfg.s
