set -o pipefail;{ cc -fplugin=/data/project/xiangzhai/dragonegg/dragonegg.so -fplugin-arg-dragonegg-emit-ir -S -o /dev/null /data/project/xiangzhai/dragonegg/test/validator/c/LongDoubleSize.c; } &&
{ cc -fplugin=/data/project/xiangzhai/dragonegg/dragonegg.so -fplugin-arg-dragonegg-emit-ir -S -o /dev/null /data/project/xiangzhai/dragonegg/test/validator/c/LongDoubleSize.c -m96bit-long-double; } &&
{ cc -fplugin=/data/project/xiangzhai/dragonegg/dragonegg.so -fplugin-arg-dragonegg-emit-ir -S -o /dev/null /data/project/xiangzhai/dragonegg/test/validator/c/LongDoubleSize.c -m128bit-long-double; }
